# Generated by Django 6.0.2 on 2026-02-20 14:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0003_remove_election_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_wallet', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_hash', models.CharField(max_length=256)),
                ('hash', models.CharField(max_length=256)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_app.candidate')),
            ],
        ),
    ]
