# Generated by Django 6.0.2 on 2026-03-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting_app", "0009_election_result_hash_election_result_publish_tx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
