# Generated by Django 6.0.2 on 2026-02-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0002_candidate_votes_election_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='description',
        ),
        migrations.AlterField(
            model_name='election',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
