# Generated by Django 6.0.2 on 2026-02-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0004_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
