# Generated by Django 6.0.2 on 2026-02-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0005_candidate_department_candidate_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='gas_used',
            field=models.IntegerField(default=21000),
        ),
    ]
